### ISSUE TITLE
Add dependency on chromaprint to provide fpcalc

### ISSUE THREAD

**Issue by ta264** [binhex/arch-lidarr#2]
We will soon (hopefully) be adding audio fingerprinting support to Lidarr.  To support this we need the `fpcalc` binary to be present on the user's path.  On Arch, I think you need to add a dependency to [chromaprint](https://www.archlinux.org/packages/extra/x86_64/chromaprint/).  Please can you add this to your image so that your users can use fingerprinting when it becomes available?  Thanks.

**Comment by binhex** [comment]
done, and built the image to make sure it builds ok.
